FROM espressif/idf:v5.4.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential \
		clang-format \
		libelf-dev \
		libjson-c-dev \
		libssl-dev \
		make \
		xxd \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /project
